/***********************************************************/
/*------------------------- USERS -------------------------*/
/***********************************************************/
/* User Table */
CREATE TABLE Users
(
    UserID          TEXT NOT NULL,
    CreationDate    TEXT,
    UserName        TEXT,
    TotalLikes      INTEGER NOT NULL DEFAULT (0),
    TipCount        INTEGER NOT NULL DEFAULT (0),
    FansRating      INTEGER,
    FunnyRating     INTEGER,
    CoolRating      INTEGER,
    AvgStarRating   DECIMAL (2, 1),
    Latitude        DECIMAL (8, 6),
    Longitude       DECIMAL (9, 6),
    PRIMARY KEY (UserID)
);

/* Link table for creating friends */
CREATE TABLE Friends
(
    User01  TEXT NOT NULL,
    User02  TEXT NOT NULL,
    FOREIGN KEY (User01) REFERENCES Users(UserID),
    FOREIGN KEY (User02) REFERENCES Users(UserID),
    PRIMARY KEY (User01, User02)
);

-- Alternate Design
CREATE TABLE Friends
(
    UserID  TEXT NOT NULL,
    FriendID  TEXT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (FriendID) REFERENCES Users(UserID),
    PRIMARY KEY (UserID, FriendID)
);


/***********************************************************/
/*----------------------- BUSINESSES ----------------------*/
/***********************************************************/
/* Businesses Table */
CREATE TABLE Business
(
    BusinessID      TEXT NOT NULL,
    BusinessName    TEXT,
    State           TEXT,
    City            TEXT,
    IsOpen          BOOLEAN,
    ReviewCount     INTEGER,
    StarRating      DECIMAL (2, 1),
    NumCheckIns     INTEGER NOT NULL DEFAULT (0),
    NumTips         INTEGER NOT NULL DEFAULT (0),
    PRIMARY KEY (BusinessID)
);

/* Business Address Table */
CREATE TABLE Addresses
(
    BusinessID  TEXT NOT NULL,
    Longitude   DECIMAL (9, 6),
    Latitude    DECIMAL (8, 6),
    Street      TEXT,
    City        TEXT,
    USState     TEXT,
    FOREIGN KEY (BusinessID) REFERENCES Business(BusinessID),
    PRIMARY KEY (BusinessID)
);

CREATE TABLE BusinessHours
(
    BusinessID      TEXT NOT NULL,
    Days            TEXT [],
    OpeningTimes    TEXT [],
    ClosingTimes    TEXT [],
    FOREIGN KEY (BusinessID) REFERENCES Business(BusinessID),
    PRIMARY KEY (BusinessID)
);

/* Basic Business Attributes Table */
CREATE TABLE BusinessAttributes
(
    BusinessID          TEXT NOT NULL,
    HasTV               BOOLEAN,
    HasWifi             BOOLEAN,
    WheelchairAccess    BOOLEAN,
    Parking             BOOLEAN [],
    PaymentMethods      BOOLEAN [],
    PriceRange          INTEGER,
    FOREIGN KEY (BusinessID) REFERENCES Business(BusinessID),
    PRIMARY KEY (BusinessID)
);

CREATE TABLE Restaurants
(
    BusinessID          TEXT NOT NULL,
    TakesReservations   BOOLEAN,
    TakeOut             BOOLEAN,
    TableService        BOOLEAN,
    KidFriendly         BOOLEAN,
    NoiseLevel          INTEGER,
    Ambiences           TEXT [],
    BestNights          BOOLEAN [7],
    MealTimes           BOOLEAN [],
    Alcohol             TEXT,
    FOREIGN KEY (BusinessID) REFERENCES Business(BusinessID),
    PRIMARY KEY (BusinessID)
);

CREATE TABLE MusicInfo
(
    BusinessID          TEXT NOT NULL,
    IsDancingFriendly   BOOLEAN,
    HasDJ               BOOLEAN,
    HasVJ               BOOLEAN,
    HasLivePerformances BOOLEAN,
    HasKaraoke          BOOLEAN,
    HasBackgroundMusic  BOOLEAN,
    FOREIGN KEY (BusinessID) REFERENCES Business(BusinessID),
    PRIMARY KEY (BusinessID)
);


/***********************************************************/
/*------------------------ REVIEWS ------------------------*/
/***********************************************************/
/* Reviews Table */
CREATE TABLE Reviews
(
    UserID          TEXT NOT NULL,
    BusinessID      TEXT NOT NULL,
    ReviewTest      TEXT,
    Likes           INTEGER,
    CreationDate    TIMESTAMP,
    FOREIGN KEY (BusinessID) REFERENCES Business(BusinessID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    PRIMARY KEY (UserID, BusinessID)
);


/***********************************************************/
/*-------------------------- MISC -------------------------*/
/***********************************************************/
/* Check Ins Table */
CREATE TABLE CheckIns
(
    BusinessID  TEXT,
    CheckInDate TIMESTAMP,
    FOREIGN KEY (BusinessID) REFERENCES Business(BusinessID),
    PRIMARY KEY (BusinessID, CheckInDate)
);

/* Tips Table */
CREATE TABLE Tips
(
    BusinessID  TEXT,
	UserID      TEXT,
    Date        TIMESTAMP,
	Likes       INTEGER,
	Text        TEXT,
    FOREIGN KEY (BusinessID) REFERENCES Business(BusinessID),
	FOREIGN KEY (UserID) REFERENCES Users(UserID),
    PRIMARY KEY (BusinessID, UserID, Date)
);

/* BusinessCategories Table */
/* NO RAGRETZ */
CREATE TABLE BusinessCategories
(
    BusinessID             TEXT NOT NULL,
    IsBars             BOOLEAN NOT NULL DEFAULT false,
    IsLingerie             BOOLEAN NOT NULL DEFAULT false,
    IsGuitarStores             BOOLEAN NOT NULL DEFAULT false,
    IsVegetarian             BOOLEAN NOT NULL DEFAULT false,
    IsHomeServices             BOOLEAN NOT NULL DEFAULT false,
    IsEmpanadas             BOOLEAN NOT NULL DEFAULT false,
    IsInternalMedicine             BOOLEAN NOT NULL DEFAULT false,
    IsAmericanTraditional             BOOLEAN NOT NULL DEFAULT false,
    IsWineBars             BOOLEAN NOT NULL DEFAULT false,
    IsHostels             BOOLEAN NOT NULL DEFAULT false,
    IsFuelDocks             BOOLEAN NOT NULL DEFAULT false,
    IsDrugstores             BOOLEAN NOT NULL DEFAULT false,
    IsKiosk             BOOLEAN NOT NULL DEFAULT false,
    IsCookingClasses             BOOLEAN NOT NULL DEFAULT false,
    IsPetTraining             BOOLEAN NOT NULL DEFAULT false,
    IsBagels             BOOLEAN NOT NULL DEFAULT false,
    IsUniversityHousing             BOOLEAN NOT NULL DEFAULT false,
    IsShoeShine             BOOLEAN NOT NULL DEFAULT false,
    IsBrazilian             BOOLEAN NOT NULL DEFAULT false,
    IsHotDogs             BOOLEAN NOT NULL DEFAULT false,
    IsPuertoRican             BOOLEAN NOT NULL DEFAULT false,
    IsCannabisClinics             BOOLEAN NOT NULL DEFAULT false,
    IsMotorcycleRepair             BOOLEAN NOT NULL DEFAULT false,
    IsHotelbar             BOOLEAN NOT NULL DEFAULT false,
    IsArtTours             BOOLEAN NOT NULL DEFAULT false,
    IsHomeAndGarden             BOOLEAN NOT NULL DEFAULT false,
    IsDentists             BOOLEAN NOT NULL DEFAULT false,
    IsSpecialtySchools             BOOLEAN NOT NULL DEFAULT false,
    IsPowderCoating             BOOLEAN NOT NULL DEFAULT false,
    IsVietnamese             BOOLEAN NOT NULL DEFAULT false,
    IsBeerGardens             BOOLEAN NOT NULL DEFAULT false,
    IsPetHospice             BOOLEAN NOT NULL DEFAULT false,
    IsIrishPub             BOOLEAN NOT NULL DEFAULT false,
    IsHorsebackRiding             BOOLEAN NOT NULL DEFAULT false,
    IsMobilePhoneAccessories             BOOLEAN NOT NULL DEFAULT false,
    IsOrthopedists             BOOLEAN NOT NULL DEFAULT false,
    IsLaotian             BOOLEAN NOT NULL DEFAULT false,
    IsAfrican             BOOLEAN NOT NULL DEFAULT false,
    IsHomeAutomation             BOOLEAN NOT NULL DEFAULT false,
    IsBeautyAndSpas             BOOLEAN NOT NULL DEFAULT false,
    IsBarbeque             BOOLEAN NOT NULL DEFAULT false,
    IsYoga             BOOLEAN NOT NULL DEFAULT false,
    IsCSA             BOOLEAN NOT NULL DEFAULT false,
    IsOrthodontists             BOOLEAN NOT NULL DEFAULT false,
    IsVegan             BOOLEAN NOT NULL DEFAULT false,
    IsMobilePhones             BOOLEAN NOT NULL DEFAULT false,
    IsTeethWhitening             BOOLEAN NOT NULL DEFAULT false,
    IsTires             BOOLEAN NOT NULL DEFAULT false,
    IsOrthotics             BOOLEAN NOT NULL DEFAULT false,
    IsEducation             BOOLEAN NOT NULL DEFAULT false,
    IsShavedIce             BOOLEAN NOT NULL DEFAULT false,
    IsHairStylists             BOOLEAN NOT NULL DEFAULT false,
    IsCarWash             BOOLEAN NOT NULL DEFAULT false,
    IsOccupationalTherapy             BOOLEAN NOT NULL DEFAULT false,
    IsFlowersAndGifts             BOOLEAN NOT NULL DEFAULT false,
    IsVirtualRealityCenters             BOOLEAN NOT NULL DEFAULT false,
    IsWatchRepair             BOOLEAN NOT NULL DEFAULT false,
    IsGayBars             BOOLEAN NOT NULL DEFAULT false,
    IsPatisserieAndCakeShop             BOOLEAN NOT NULL DEFAULT false,
    IsGolfLessons             BOOLEAN NOT NULL DEFAULT false,
    IsChinese             BOOLEAN NOT NULL DEFAULT false,
    IsTaiwanese             BOOLEAN NOT NULL DEFAULT false,
    IsPizza             BOOLEAN NOT NULL DEFAULT false,
    IsCardsAndStationery             BOOLEAN NOT NULL DEFAULT false,
    IsBlowDryOutServices             BOOLEAN NOT NULL DEFAULT false,
    IsGyms             BOOLEAN NOT NULL DEFAULT false,
    IsElectronicsRepair             BOOLEAN NOT NULL DEFAULT false,
    IsJuiceBarsAndSmoothies             BOOLEAN NOT NULL DEFAULT false,
    IsFoodCourt             BOOLEAN NOT NULL DEFAULT false,
    IsHolidayDecorations             BOOLEAN NOT NULL DEFAULT false,
    IsPlaygrounds             BOOLEAN NOT NULL DEFAULT false,
    IsLawyers             BOOLEAN NOT NULL DEFAULT false,
    IsTeaRooms             BOOLEAN NOT NULL DEFAULT false,
    IsLeisureCenters             BOOLEAN NOT NULL DEFAULT false,
    IsHobbyShops             BOOLEAN NOT NULL DEFAULT false,
    IsArtClasses             BOOLEAN NOT NULL DEFAULT false,
    IsSpecialtyFood             BOOLEAN NOT NULL DEFAULT false,
    IsSprayTanning             BOOLEAN NOT NULL DEFAULT false,
    IsMovers             BOOLEAN NOT NULL DEFAULT false,
    IsCideries             BOOLEAN NOT NULL DEFAULT false,
    IsLivestockFeedAndSupply             BOOLEAN NOT NULL DEFAULT false,
    IsMassage             BOOLEAN NOT NULL DEFAULT false,
    IsAnimalShelters             BOOLEAN NOT NULL DEFAULT false,
    IsFrench             BOOLEAN NOT NULL DEFAULT false,
    IsCarDealers             BOOLEAN NOT NULL DEFAULT false,
    IsPoutineries             BOOLEAN NOT NULL DEFAULT false,
    IsSharedOfficeSpaces             BOOLEAN NOT NULL DEFAULT false,
    IsLandscaping             BOOLEAN NOT NULL DEFAULT false,
    IsAquariumServices             BOOLEAN NOT NULL DEFAULT false,
    IsPets             BOOLEAN NOT NULL DEFAULT false,
    IsPublicServicesAndGovernment             BOOLEAN NOT NULL DEFAULT false,
    IsHeatingAndAirConditioningHVAC             BOOLEAN NOT NULL DEFAULT false,
    IsBoating             BOOLEAN NOT NULL DEFAULT false,
    IsCarpetInstallation             BOOLEAN NOT NULL DEFAULT false,
    IsAestheticians             BOOLEAN NOT NULL DEFAULT false,
    IsGolf             BOOLEAN NOT NULL DEFAULT false,
    IsHomeCleaning             BOOLEAN NOT NULL DEFAULT false,
    IsCinema             BOOLEAN NOT NULL DEFAULT false,
    IsEmergencyMedicine             BOOLEAN NOT NULL DEFAULT false,
    IsPassportAndVisaServices             BOOLEAN NOT NULL DEFAULT false,
    IsSandwiches             BOOLEAN NOT NULL DEFAULT false,
    IsAmericanNew             BOOLEAN NOT NULL DEFAULT false,
    IsAutoUpholstery             BOOLEAN NOT NULL DEFAULT false,
    IsVeterinarians             BOOLEAN NOT NULL DEFAULT false,
    IsCommunityServiceNonProfit             BOOLEAN NOT NULL DEFAULT false,
    IsWraps             BOOLEAN NOT NULL DEFAULT false,
    IsHotPot             BOOLEAN NOT NULL DEFAULT false,
    IsPanAsian             BOOLEAN NOT NULL DEFAULT false,
    IsSpeechTherapists             BOOLEAN NOT NULL DEFAULT false,
    IsLiveRawFood             BOOLEAN NOT NULL DEFAULT false,
    IsFarmersMarket             BOOLEAN NOT NULL DEFAULT false,
    IsEventPlanningAndServices             BOOLEAN NOT NULL DEFAULT false,
    IsMedicalTransportation             BOOLEAN NOT NULL DEFAULT false,
    IsPersonalShopping             BOOLEAN NOT NULL DEFAULT false,
    IsStadiumsAndArenas             BOOLEAN NOT NULL DEFAULT false,
    IsCabinetry             BOOLEAN NOT NULL DEFAULT false,
    IsSushiBars             BOOLEAN NOT NULL DEFAULT false,
    IsHotTubAndPool             BOOLEAN NOT NULL DEFAULT false,
    IsSummerCamps             BOOLEAN NOT NULL DEFAULT false,
    IsBotanicalGardens             BOOLEAN NOT NULL DEFAULT false,
    IsWalkinClinics             BOOLEAN NOT NULL DEFAULT false,
    IsSportsBars             BOOLEAN NOT NULL DEFAULT false,
    IsCarStereoInstallation             BOOLEAN NOT NULL DEFAULT false,
    IsHeadShops             BOOLEAN NOT NULL DEFAULT false,
    IsDoctors             BOOLEAN NOT NULL DEFAULT false,
    IsCosmeticSurgeons             BOOLEAN NOT NULL DEFAULT false,
    IsMakeupArtists             BOOLEAN NOT NULL DEFAULT false,
    IsSelfdefenseClasses             BOOLEAN NOT NULL DEFAULT false,
    IsImportedFood             BOOLEAN NOT NULL DEFAULT false,
    IsTiling             BOOLEAN NOT NULL DEFAULT false,
    IsMobilePhoneRepair             BOOLEAN NOT NULL DEFAULT false,
    IsGoKarts             BOOLEAN NOT NULL DEFAULT false,
    IsBistros             BOOLEAN NOT NULL DEFAULT false,
    IsMortgageLenders             BOOLEAN NOT NULL DEFAULT false,
    IsCardioClasses             BOOLEAN NOT NULL DEFAULT false,
    IsDiagnosticServices             BOOLEAN NOT NULL DEFAULT false,
    IsDominican             BOOLEAN NOT NULL DEFAULT false,
    IsBuildingSupplies             BOOLEAN NOT NULL DEFAULT false,
    IsObservatories             BOOLEAN NOT NULL DEFAULT false,
    IsDonuts             BOOLEAN NOT NULL DEFAULT false,
    IsPetAdoption             BOOLEAN NOT NULL DEFAULT false,
    IsEyewearAndOpticians             BOOLEAN NOT NULL DEFAULT false,
    IsEarNoseAndThroat             BOOLEAN NOT NULL DEFAULT false,
    IsBookstores             BOOLEAN NOT NULL DEFAULT false,
    IsMusicAndVideo             BOOLEAN NOT NULL DEFAULT false,
    IsCarBuyers             BOOLEAN NOT NULL DEFAULT false,
    IsRVDealers             BOOLEAN NOT NULL DEFAULT false,
    IsTubing             BOOLEAN NOT NULL DEFAULT false,
    IsEyebrowServices             BOOLEAN NOT NULL DEFAULT false,
    IsTrampolineParks             BOOLEAN NOT NULL DEFAULT false,
    IsReiki             BOOLEAN NOT NULL DEFAULT false,
    IsNewMexicanCuisine             BOOLEAN NOT NULL DEFAULT false,
    IsArtsAndEntertainment             BOOLEAN NOT NULL DEFAULT false,
    IsCoffeeAndTea             BOOLEAN NOT NULL DEFAULT false,
    IsBankruptcyLaw             BOOLEAN NOT NULL DEFAULT false,
    IsCurrencyExchange             BOOLEAN NOT NULL DEFAULT false,
    IsGeneralDentistry             BOOLEAN NOT NULL DEFAULT false,
    IsMidwives             BOOLEAN NOT NULL DEFAULT false,
    IsCheckCashingAndPaydayLoans             BOOLEAN NOT NULL DEFAULT false,
    IsScandinavian             BOOLEAN NOT NULL DEFAULT false,
    IsParks             BOOLEAN NOT NULL DEFAULT false,
    IsMasonryConcrete             BOOLEAN NOT NULL DEFAULT false,
    IsMusicAndDVDs             BOOLEAN NOT NULL DEFAULT false,
    IsArtMuseums             BOOLEAN NOT NULL DEFAULT false,
    IsClubCrawl             BOOLEAN NOT NULL DEFAULT false,
    IsVitaminsAndSupplements             BOOLEAN NOT NULL DEFAULT false,
    IsUkrainian             BOOLEAN NOT NULL DEFAULT false,
    IsFoodTrucks             BOOLEAN NOT NULL DEFAULT false,
    IsEscapeGames             BOOLEAN NOT NULL DEFAULT false,
    IsEmergencyPetHospital             BOOLEAN NOT NULL DEFAULT false,
    IsBrewpubs             BOOLEAN NOT NULL DEFAULT false,
    IsHomeDecor             BOOLEAN NOT NULL DEFAULT false,
    IsBeerGarden             BOOLEAN NOT NULL DEFAULT false,
    IsUsed             BOOLEAN NOT NULL DEFAULT false,
    IsBritish             BOOLEAN NOT NULL DEFAULT false,
    IsHotelsAndTravel             BOOLEAN NOT NULL DEFAULT false,
    IsOliveOil             BOOLEAN NOT NULL DEFAULT false,
    IsGunRifleRanges             BOOLEAN NOT NULL DEFAULT false,
    IsLaboratoryTesting             BOOLEAN NOT NULL DEFAULT false,
    IsMiddleEastern             BOOLEAN NOT NULL DEFAULT false,
    IsBartenders             BOOLEAN NOT NULL DEFAULT false,
    IsFondue             BOOLEAN NOT NULL DEFAULT false,
    IsWeddingChapels             BOOLEAN NOT NULL DEFAULT false,
    IsButcher             BOOLEAN NOT NULL DEFAULT false,
    IsSelfStorage             BOOLEAN NOT NULL DEFAULT false,
    IsDryCleaning             BOOLEAN NOT NULL DEFAULT false,
    IsWigs             BOOLEAN NOT NULL DEFAULT false,
    IsHairLossCenters             BOOLEAN NOT NULL DEFAULT false,
    IsGoldBuyers             BOOLEAN NOT NULL DEFAULT false,
    IsTours             BOOLEAN NOT NULL DEFAULT false,
    IsGrocery             BOOLEAN NOT NULL DEFAULT false,
    IsMarketing             BOOLEAN NOT NULL DEFAULT false,
    IsFloatSpa             BOOLEAN NOT NULL DEFAULT false,
    IsSeafood             BOOLEAN NOT NULL DEFAULT false,
    IsChickenShop             BOOLEAN NOT NULL DEFAULT false,
    IsInternetCafes             BOOLEAN NOT NULL DEFAULT false,
    IsBurmese             BOOLEAN NOT NULL DEFAULT false,
    IsRestaurants             BOOLEAN NOT NULL DEFAULT false,
    IsAntiques             BOOLEAN NOT NULL DEFAULT false,
    IsTransportation             BOOLEAN NOT NULL DEFAULT false,
    IsArgentine             BOOLEAN NOT NULL DEFAULT false,
    IsTabletopGames             BOOLEAN NOT NULL DEFAULT false,
    IsCarBrokers             BOOLEAN NOT NULL DEFAULT false,
    IsArmenian             BOOLEAN NOT NULL DEFAULT false,
    IsKickboxing             BOOLEAN NOT NULL DEFAULT false,
    IsBoatDealers             BOOLEAN NOT NULL DEFAULT false,
    IsPita             BOOLEAN NOT NULL DEFAULT false,
    IsAirlines             BOOLEAN NOT NULL DEFAULT false,
    IsJunkRemovalAndHauling             BOOLEAN NOT NULL DEFAULT false,
    IsScreenPrinting             BOOLEAN NOT NULL DEFAULT false,
    IsTransmissionRepair             BOOLEAN NOT NULL DEFAULT false,
    IsChildrensClothing             BOOLEAN NOT NULL DEFAULT false,
    IsWaterStores             BOOLEAN NOT NULL DEFAULT false,
    IsMassageSchools             BOOLEAN NOT NULL DEFAULT false,
    IsCouriersAndDeliveryServices             BOOLEAN NOT NULL DEFAULT false,
    IsStreetVendors             BOOLEAN NOT NULL DEFAULT false,
    IsBootCamps             BOOLEAN NOT NULL DEFAULT false,
    IsDiscountStore             BOOLEAN NOT NULL DEFAULT false,
    IsThai             BOOLEAN NOT NULL DEFAULT false,
    IsLiveAndRawFood             BOOLEAN NOT NULL DEFAULT false,
    IsRussian             BOOLEAN NOT NULL DEFAULT false,
    IsMaternityWear             BOOLEAN NOT NULL DEFAULT false,
    IsServiceStations             BOOLEAN NOT NULL DEFAULT false,
    IsDentalHygienists             BOOLEAN NOT NULL DEFAULT false,
    IsCheesesteaks             BOOLEAN NOT NULL DEFAULT false,
    IsCaribbean             BOOLEAN NOT NULL DEFAULT false,
    IsBakeries             BOOLEAN NOT NULL DEFAULT false,
    IsFabricStores             BOOLEAN NOT NULL DEFAULT false,
    IsNursePractitioner             BOOLEAN NOT NULL DEFAULT false,
    IsVideosAndVideoGameRental             BOOLEAN NOT NULL DEFAULT false,
    IsDamageRestoration             BOOLEAN NOT NULL DEFAULT false,
    IsCosmeticsAndBeautySupply             BOOLEAN NOT NULL DEFAULT false,
    IsHennaArtists             BOOLEAN NOT NULL DEFAULT false,
    IsCollegeCounseling             BOOLEAN NOT NULL DEFAULT false,
    IsCannabisDispensaries             BOOLEAN NOT NULL DEFAULT false,
    IsWineTastingRoom             BOOLEAN NOT NULL DEFAULT false,
    IsYelpEvents             BOOLEAN NOT NULL DEFAULT false,
    IsCigarBars             BOOLEAN NOT NULL DEFAULT false,
    IsSpanish             BOOLEAN NOT NULL DEFAULT false,
    IsOptometrists             BOOLEAN NOT NULL DEFAULT false,
    IsPianoServices             BOOLEAN NOT NULL DEFAULT false,
    IsLightingStores             BOOLEAN NOT NULL DEFAULT false,
    IsCountertopInstallation             BOOLEAN NOT NULL DEFAULT false,
    IsSportsWear             BOOLEAN NOT NULL DEFAULT false,
    IsBasque             BOOLEAN NOT NULL DEFAULT false,
    IsFitnessExerciseEquipment             BOOLEAN NOT NULL DEFAULT false,
    IsKitchenIncubators             BOOLEAN NOT NULL DEFAULT false,
    IsSingaporean             BOOLEAN NOT NULL DEFAULT false,
    IsPublicTransportation             BOOLEAN NOT NULL DEFAULT false,
    IsCommercialTruckDealers             BOOLEAN NOT NULL DEFAULT false,
    IsDiveBars             BOOLEAN NOT NULL DEFAULT false,
    IsConciergeMedicine             BOOLEAN NOT NULL DEFAULT false,
    IsAirports             BOOLEAN NOT NULL DEFAULT false,
    IsCustomizedMerchandise             BOOLEAN NOT NULL DEFAULT false,
    IsPartyEquipmentRentals             BOOLEAN NOT NULL DEFAULT false,
    IsBrewingSupplies             BOOLEAN NOT NULL DEFAULT false,
    IsDelicatessen             BOOLEAN NOT NULL DEFAULT false,
    IsSkinCare             BOOLEAN NOT NULL DEFAULT false,
    IsTurkish             BOOLEAN NOT NULL DEFAULT false,
    IsVisitorCenters             BOOLEAN NOT NULL DEFAULT false,
    IsTapasBars             BOOLEAN NOT NULL DEFAULT false,
    IsTeacherSupplies             BOOLEAN NOT NULL DEFAULT false,
    IsHungarian             BOOLEAN NOT NULL DEFAULT false,
    IsWaxing             BOOLEAN NOT NULL DEFAULT false,
    IsCajunAndCreole             BOOLEAN NOT NULL DEFAULT false,
    IsLandmarksAndHistoricalBuildings             BOOLEAN NOT NULL DEFAULT false,
    IsSkydiving             BOOLEAN NOT NULL DEFAULT false,
    IsConveyorBeltSushi             BOOLEAN NOT NULL DEFAULT false,
    IsSunglasses             BOOLEAN NOT NULL DEFAULT false,
    IsBoxing             BOOLEAN NOT NULL DEFAULT false,
    IsElectricitySuppliers             BOOLEAN NOT NULL DEFAULT false,
    IsGerman             BOOLEAN NOT NULL DEFAULT false,
    IsArcades             BOOLEAN NOT NULL DEFAULT false,
    IsReflexology             BOOLEAN NOT NULL DEFAULT false,
    IsCookingSchools             BOOLEAN NOT NULL DEFAULT false,
    IsTelevisionServiceProviders             BOOLEAN NOT NULL DEFAULT false,
    IsSaunas             BOOLEAN NOT NULL DEFAULT false,
    IsBeaches             BOOLEAN NOT NULL DEFAULT false,
    IsBasketballCourts             BOOLEAN NOT NULL DEFAULT false,
    IsHybridCarRepair             BOOLEAN NOT NULL DEFAULT false,
    IsMalaysian             BOOLEAN NOT NULL DEFAULT false,
    IsPharmacy             BOOLEAN NOT NULL DEFAULT false,
    IsAirportTerminals             BOOLEAN NOT NULL DEFAULT false,
    IsShanghainese             BOOLEAN NOT NULL DEFAULT false,
    IsGunAndRifleRanges             BOOLEAN NOT NULL DEFAULT false,
    IsIceCreamAndFrozenYogurt             BOOLEAN NOT NULL DEFAULT false,
    IsRehabilitationCenter             BOOLEAN NOT NULL DEFAULT false,
    IsGymnastics             BOOLEAN NOT NULL DEFAULT false,
    IsRugs             BOOLEAN NOT NULL DEFAULT false,
    IsHydrotherapy             BOOLEAN NOT NULL DEFAULT false,
    IsSportsClubs             BOOLEAN NOT NULL DEFAULT false,
    IsMusicalInstrumentServices             BOOLEAN NOT NULL DEFAULT false,
    IsTanningBeds             BOOLEAN NOT NULL DEFAULT false,
    IsTruckRental             BOOLEAN NOT NULL DEFAULT false,
    IsDanceStudios             BOOLEAN NOT NULL DEFAULT false,
    IsAutomotive             BOOLEAN NOT NULL DEFAULT false,
    IsCoffeeshops             BOOLEAN NOT NULL DEFAULT false,
    IsHairRemoval             BOOLEAN NOT NULL DEFAULT false,
    IsArtGalleries             BOOLEAN NOT NULL DEFAULT false,
    IsCriminalDefenseLaw             BOOLEAN NOT NULL DEFAULT false,
    IsDivorceAndFamilyLaw             BOOLEAN NOT NULL DEFAULT false,
    IsCafeteria             BOOLEAN NOT NULL DEFAULT false,
    IsHimalayanNepalese             BOOLEAN NOT NULL DEFAULT false,
    IsBeverageStore             BOOLEAN NOT NULL DEFAULT false,
    IsBarbers             BOOLEAN NOT NULL DEFAULT false,
    IsEmergencyRooms             BOOLEAN NOT NULL DEFAULT false,
    IsPetCremationServices             BOOLEAN NOT NULL DEFAULT false,
    IsCondominiums             BOOLEAN NOT NULL DEFAULT false,
    IsGolfEquipmentShops             BOOLEAN NOT NULL DEFAULT false,
    IsPeruvian             BOOLEAN NOT NULL DEFAULT false,
    IsBlowDryAndOutServices             BOOLEAN NOT NULL DEFAULT false,
    IsCommercialTruckRepair             BOOLEAN NOT NULL DEFAULT false,
    IsAppliances             BOOLEAN NOT NULL DEFAULT false,
    IsNailSalons             BOOLEAN NOT NULL DEFAULT false,
    IsAmateurSportsTeams             BOOLEAN NOT NULL DEFAULT false,
    IsCarInspectors             BOOLEAN NOT NULL DEFAULT false,
    IsBeerBar             BOOLEAN NOT NULL DEFAULT false,
    IsBrasseries             BOOLEAN NOT NULL DEFAULT false,
    IsAccessories             BOOLEAN NOT NULL DEFAULT false,
    IsLaserEyeSurgeryLasik             BOOLEAN NOT NULL DEFAULT false,
    IsTrailerRepair             BOOLEAN NOT NULL DEFAULT false,
    IsFurnitureReupholstery             BOOLEAN NOT NULL DEFAULT false,
    IsUtilities             BOOLEAN NOT NULL DEFAULT false,
    IsAutoGlassServices             BOOLEAN NOT NULL DEFAULT false,
    IsSwimwear             BOOLEAN NOT NULL DEFAULT false,
    IsColombian             BOOLEAN NOT NULL DEFAULT false,
    IsFoodBanks             BOOLEAN NOT NULL DEFAULT false,
    IsOxygenBars             BOOLEAN NOT NULL DEFAULT false,
    IsFoodStands             BOOLEAN NOT NULL DEFAULT false,
    IsPretzels             BOOLEAN NOT NULL DEFAULT false,
    IsSmogCheckStations             BOOLEAN NOT NULL DEFAULT false,
    IsPerformingArts             BOOLEAN NOT NULL DEFAULT false,
    IsHuntingAndFishingSupplies             BOOLEAN NOT NULL DEFAULT false,
    IsBodyContouring             BOOLEAN NOT NULL DEFAULT false,
    IsKidsHairSalons             BOOLEAN NOT NULL DEFAULT false,
    IsUzbek             BOOLEAN NOT NULL DEFAULT false,
    IsPetBreeders             BOOLEAN NOT NULL DEFAULT false,
    IsPainManagement             BOOLEAN NOT NULL DEFAULT false,
    IsDepartmentsofMotorVehicles             BOOLEAN NOT NULL DEFAULT false,
    IsZoos             BOOLEAN NOT NULL DEFAULT false,
    IsPropertyManagement             BOOLEAN NOT NULL DEFAULT false,
    IsAutoPartsAndSupplies             BOOLEAN NOT NULL DEFAULT false,
    IsPeriodontists             BOOLEAN NOT NULL DEFAULT false,
    IsBikeRepairMaintenance             BOOLEAN NOT NULL DEFAULT false,
    IsDiners             BOOLEAN NOT NULL DEFAULT false,
    IsInsurance             BOOLEAN NOT NULL DEFAULT false,
    IsChildrensMuseums             BOOLEAN NOT NULL DEFAULT false,
    IsFalafel             BOOLEAN NOT NULL DEFAULT false,
    IsUniforms             BOOLEAN NOT NULL DEFAULT false,
    IsAutoLoanProviders             BOOLEAN NOT NULL DEFAULT false,
    IsBounceHouseRentals             BOOLEAN NOT NULL DEFAULT false,
    IsCosmetologySchools             BOOLEAN NOT NULL DEFAULT false,
    IsPakistani             BOOLEAN NOT NULL DEFAULT false,
    IsMexican             BOOLEAN NOT NULL DEFAULT false,
    IsStripClubs             BOOLEAN NOT NULL DEFAULT false,
    IsRegistrationServices             BOOLEAN NOT NULL DEFAULT false,
    IsVocationalAndTechnicalSchool             BOOLEAN NOT NULL DEFAULT false,
    IsRealEstateServices             BOOLEAN NOT NULL DEFAULT false,
    IsWeightLossCenters             BOOLEAN NOT NULL DEFAULT false,
    IsModernEuropean             BOOLEAN NOT NULL DEFAULT false,
    IsArtSchools             BOOLEAN NOT NULL DEFAULT false,
    IsHiking             BOOLEAN NOT NULL DEFAULT false,
    IsMuseums             BOOLEAN NOT NULL DEFAULT false,
    IsDataRecovery             BOOLEAN NOT NULL DEFAULT false,
    IsAdult             BOOLEAN NOT NULL DEFAULT false,
    IsIrrigation             BOOLEAN NOT NULL DEFAULT false,
    IsPoolAndHotTubService             BOOLEAN NOT NULL DEFAULT false,
    IsKnittingSupplies             BOOLEAN NOT NULL DEFAULT false,
    IsKorean             BOOLEAN NOT NULL DEFAULT false,
    IsPartyAndEventPlanning             BOOLEAN NOT NULL DEFAULT false,
    IsHairExtensions             BOOLEAN NOT NULL DEFAULT false,
    IsCountryDanceHalls             BOOLEAN NOT NULL DEFAULT false,
    IsPetGroomers             BOOLEAN NOT NULL DEFAULT false,
    IsFishAndChips             BOOLEAN NOT NULL DEFAULT false,
    IsCarWindowTinting             BOOLEAN NOT NULL DEFAULT false,
    IsLightingFixturesAndEquipment             BOOLEAN NOT NULL DEFAULT false,
    IsBabyGearAndFurniture             BOOLEAN NOT NULL DEFAULT false,
    IsTeamBuildingActivities             BOOLEAN NOT NULL DEFAULT false,
    IsTattooRemoval             BOOLEAN NOT NULL DEFAULT false,
    IsDriveInTheater             BOOLEAN NOT NULL DEFAULT false,
    IsLakes             BOOLEAN NOT NULL DEFAULT false,
    IsRecyclingCenter             BOOLEAN NOT NULL DEFAULT false,
    IsChampagneBars             BOOLEAN NOT NULL DEFAULT false,
    IsWaterParks             BOOLEAN NOT NULL DEFAULT false,
    IsBloodAndPlasmaDonationCenters             BOOLEAN NOT NULL DEFAULT false,
    IsTanning             BOOLEAN NOT NULL DEFAULT false,
    IsShoppingCenters             BOOLEAN NOT NULL DEFAULT false,
    IsChildCareAndDayCare             BOOLEAN NOT NULL DEFAULT false,
    IsKombucha             BOOLEAN NOT NULL DEFAULT false,
    IsVacationRentalAgents             BOOLEAN NOT NULL DEFAULT false,
    IsDogParks             BOOLEAN NOT NULL DEFAULT false,
    IsApartments             BOOLEAN NOT NULL DEFAULT false,
    IsMusicVenues             BOOLEAN NOT NULL DEFAULT false,
    IsSportsMedicine             BOOLEAN NOT NULL DEFAULT false,
    IsIntervalTrainingGyms             BOOLEAN NOT NULL DEFAULT false,
    IsHomeAndRentalInsurance             BOOLEAN NOT NULL DEFAULT false,
    IsFlorists             BOOLEAN NOT NULL DEFAULT false,
    IsTowing             BOOLEAN NOT NULL DEFAULT false,
    IsGardeners             BOOLEAN NOT NULL DEFAULT false,
    IsGarageDoorServices             BOOLEAN NOT NULL DEFAULT false,
    IsIzakaya             BOOLEAN NOT NULL DEFAULT false,
    IsRestaurantSupplies             BOOLEAN NOT NULL DEFAULT false,
    IsPianoStores             BOOLEAN NOT NULL DEFAULT false,
    IsSoup             BOOLEAN NOT NULL DEFAULT false,
    IsMartialArts             BOOLEAN NOT NULL DEFAULT false,
    IsMeditationCenters             BOOLEAN NOT NULL DEFAULT false,
    IsActiveLife             BOOLEAN NOT NULL DEFAULT false,
    IsCommunityCenters             BOOLEAN NOT NULL DEFAULT false,
    IsPersonalChefs             BOOLEAN NOT NULL DEFAULT false,
    IsSteakhouses             BOOLEAN NOT NULL DEFAULT false,
    IsMailboxCenters             BOOLEAN NOT NULL DEFAULT false,
    IsLounges             BOOLEAN NOT NULL DEFAULT false,
    IsVenezuelan             BOOLEAN NOT NULL DEFAULT false,
    IsRVRepair             BOOLEAN NOT NULL DEFAULT false,
    IsFestivals             BOOLEAN NOT NULL DEFAULT false,
    IsMunicipality             BOOLEAN NOT NULL DEFAULT false,
    IsNailTechnicians             BOOLEAN NOT NULL DEFAULT false,
    IsEducationalServices             BOOLEAN NOT NULL DEFAULT false,
    IsNutritionists             BOOLEAN NOT NULL DEFAULT false,
    IsMongolian             BOOLEAN NOT NULL DEFAULT false,
    IsPestControl             BOOLEAN NOT NULL DEFAULT false,
    IsIndian             BOOLEAN NOT NULL DEFAULT false,
    IsRoadsideAssistance             BOOLEAN NOT NULL DEFAULT false,
    IsScreenPrintingAndTShirtPrinting             BOOLEAN NOT NULL DEFAULT false,
    IsCafes             BOOLEAN NOT NULL DEFAULT false,
    IsTapasSmallPlates             BOOLEAN NOT NULL DEFAULT false,
    IsShopping             BOOLEAN NOT NULL DEFAULT false,
    IsSoulFood             BOOLEAN NOT NULL DEFAULT false,
    IsPoke             BOOLEAN NOT NULL DEFAULT false,
    IsPawnShops             BOOLEAN NOT NULL DEFAULT false,
    IsCocktailBars             BOOLEAN NOT NULL DEFAULT false,
    IsHealthAndMedical             BOOLEAN NOT NULL DEFAULT false,
    IsTeppanyaki             BOOLEAN NOT NULL DEFAULT false,
    IsCarpeting             BOOLEAN NOT NULL DEFAULT false,
    IsWaffles             BOOLEAN NOT NULL DEFAULT false,
    IsDepartmentStores             BOOLEAN NOT NULL DEFAULT false,
    IsSmokehouse             BOOLEAN NOT NULL DEFAULT false,
    IsBoatCharters             BOOLEAN NOT NULL DEFAULT false,
    IsPrintingServices             BOOLEAN NOT NULL DEFAULT false,
    IsPetBoarding             BOOLEAN NOT NULL DEFAULT false,
    IsAustralian             BOOLEAN NOT NULL DEFAULT false,
    IsTelecommunications             BOOLEAN NOT NULL DEFAULT false,
    IsVacationRentals             BOOLEAN NOT NULL DEFAULT false,
    IsPartySupplies             BOOLEAN NOT NULL DEFAULT false,
    IsLuggage             BOOLEAN NOT NULL DEFAULT false,
    IsPersonalInjuryLaw             BOOLEAN NOT NULL DEFAULT false,
    IsCreperies             BOOLEAN NOT NULL DEFAULT false,
    IsBooks             BOOLEAN NOT NULL DEFAULT false,
    IsGelato             BOOLEAN NOT NULL DEFAULT false,
    IsComfortFood             BOOLEAN NOT NULL DEFAULT false,
    IsOrganicStores             BOOLEAN NOT NULL DEFAULT false,
    IsDoItYourselfFood             BOOLEAN NOT NULL DEFAULT false,
    IsCollegesAndUniversities             BOOLEAN NOT NULL DEFAULT false,
    IsCoffeeRoasteries             BOOLEAN NOT NULL DEFAULT false,
    IsDimSum             BOOLEAN NOT NULL DEFAULT false,
    IsPediatricians             BOOLEAN NOT NULL DEFAULT false,
    IsFruitsAndVeggies             BOOLEAN NOT NULL DEFAULT false,
    IsClimbing             BOOLEAN NOT NULL DEFAULT false,
    IsPopupShops             BOOLEAN NOT NULL DEFAULT false,
    IsPolish             BOOLEAN NOT NULL DEFAULT false,
    IsMedicalCenters             BOOLEAN NOT NULL DEFAULT false,
    IsTacos             BOOLEAN NOT NULL DEFAULT false,
    IsSynagogues             BOOLEAN NOT NULL DEFAULT false,
    IsPettingZoos             BOOLEAN NOT NULL DEFAULT false,
    IsFinancialAdvising             BOOLEAN NOT NULL DEFAULT false,
    IsTelevisionStations             BOOLEAN NOT NULL DEFAULT false,
    IsSoccer             BOOLEAN NOT NULL DEFAULT false,
    IsSpiritualShop             BOOLEAN NOT NULL DEFAULT false,
    IsPlumbing             BOOLEAN NOT NULL DEFAULT false,
    IsPaintYourOwnPottery             BOOLEAN NOT NULL DEFAULT false,
    IsPoolCleaners             BOOLEAN NOT NULL DEFAULT false,
    IsComedyClubs             BOOLEAN NOT NULL DEFAULT false,
    IsHydrojetting             BOOLEAN NOT NULL DEFAULT false,
    IsITServicesAndComputerRepair             BOOLEAN NOT NULL DEFAULT false,
    IsGlutenFree             BOOLEAN NOT NULL DEFAULT false,
    IsFamilyPractice             BOOLEAN NOT NULL DEFAULT false,
    IsEstheticians             BOOLEAN NOT NULL DEFAULT false,
    IsRaftingKayaking             BOOLEAN NOT NULL DEFAULT false,
    IsCourthouses             BOOLEAN NOT NULL DEFAULT false,
    IsCarRental             BOOLEAN NOT NULL DEFAULT false,
    IsOfficeEquipment             BOOLEAN NOT NULL DEFAULT false,
    IsComputers             BOOLEAN NOT NULL DEFAULT false,
    IsNaturopathicHolistic             BOOLEAN NOT NULL DEFAULT false,
    IsPhotographyStoresAndServices             BOOLEAN NOT NULL DEFAULT false,
    IsShippingCenters             BOOLEAN NOT NULL DEFAULT false,
    IsGastropubs             BOOLEAN NOT NULL DEFAULT false,
    IsSpineSurgeons             BOOLEAN NOT NULL DEFAULT false,
    IsVehicleWraps             BOOLEAN NOT NULL DEFAULT false,
    IsCyclingClasses             BOOLEAN NOT NULL DEFAULT false,
    IsBelgian             BOOLEAN NOT NULL DEFAULT false,
    IsRecordingAndRehearsalStudios             BOOLEAN NOT NULL DEFAULT false,
    IsPoolHalls             BOOLEAN NOT NULL DEFAULT false,
    IsEthnicGrocery             BOOLEAN NOT NULL DEFAULT false,
    IsProsthodontists             BOOLEAN NOT NULL DEFAULT false,
    IsPublicMarkets             BOOLEAN NOT NULL DEFAULT false,
    IsChickenWings             BOOLEAN NOT NULL DEFAULT false,
    IsGiftShops             BOOLEAN NOT NULL DEFAULT false,
    IsKosher             BOOLEAN NOT NULL DEFAULT false,
    IsPersianIranian             BOOLEAN NOT NULL DEFAULT false,
    IsFitnessAndInstruction             BOOLEAN NOT NULL DEFAULT false,
    IsItalian             BOOLEAN NOT NULL DEFAULT false,
    IsDogWalkers             BOOLEAN NOT NULL DEFAULT false,
    IsCuban             BOOLEAN NOT NULL DEFAULT false,
    IsBeer             BOOLEAN NOT NULL DEFAULT false,
    IsVapeShops             BOOLEAN NOT NULL DEFAULT false,
    IsConvenienceStores             BOOLEAN NOT NULL DEFAULT false,
    IsAutoInsurance             BOOLEAN NOT NULL DEFAULT false,
    IsMetalFabricators             BOOLEAN NOT NULL DEFAULT false,
    IsTableware             BOOLEAN NOT NULL DEFAULT false,
    IsUsedCarDealers             BOOLEAN NOT NULL DEFAULT false,
    IsMassMedia             BOOLEAN NOT NULL DEFAULT false,
    IsBubbleTea             BOOLEAN NOT NULL DEFAULT false,
    IsLibraries             BOOLEAN NOT NULL DEFAULT false,
    IsVenuesAndEventSpaces             BOOLEAN NOT NULL DEFAULT false,
    IsAirportShuttles             BOOLEAN NOT NULL DEFAULT false,
    IsTrinidadian             BOOLEAN NOT NULL DEFAULT false,
    IsDelis             BOOLEAN NOT NULL DEFAULT false,
    IsWeddingPlanning             BOOLEAN NOT NULL DEFAULT false,
    IsCajunCreole             BOOLEAN NOT NULL DEFAULT false,
    IsAquariums             BOOLEAN NOT NULL DEFAULT false,
    IsSewingAndAlterations             BOOLEAN NOT NULL DEFAULT false,
    IsProfessionalSportsTeams             BOOLEAN NOT NULL DEFAULT false,
    IsBirdShops             BOOLEAN NOT NULL DEFAULT false,
    IsCantonese             BOOLEAN NOT NULL DEFAULT false,
    IsLaserHairRemoval             BOOLEAN NOT NULL DEFAULT false,
    IsSkatingRinks             BOOLEAN NOT NULL DEFAULT false,
    IsCupcakes             BOOLEAN NOT NULL DEFAULT false,
    IsWorkersCompensationLaw             BOOLEAN NOT NULL DEFAULT false,
    IsVideoGameStores             BOOLEAN NOT NULL DEFAULT false,
    IsWindshieldInstallationAndRepair             BOOLEAN NOT NULL DEFAULT false,
    IsCommercialRealEstate             BOOLEAN NOT NULL DEFAULT false,
    IsHomeWindowTinting             BOOLEAN NOT NULL DEFAULT false,
    IsBreakfastAndBrunch             BOOLEAN NOT NULL DEFAULT false,
    IsPermanentMakeup             BOOLEAN NOT NULL DEFAULT false,
    IsVintageAndConsignment             BOOLEAN NOT NULL DEFAULT false,
    IsAfghan             BOOLEAN NOT NULL DEFAULT false,
    IsPortuguese             BOOLEAN NOT NULL DEFAULT false,
    IsFraming             BOOLEAN NOT NULL DEFAULT false,
    IsKidsActivities             BOOLEAN NOT NULL DEFAULT false,
    IsTicketSales             BOOLEAN NOT NULL DEFAULT false,
    IsMobileDentRepair             BOOLEAN NOT NULL DEFAULT false,
    IsCostumes             BOOLEAN NOT NULL DEFAULT false,
    IsHorseRacing             BOOLEAN NOT NULL DEFAULT false,
    IsBreweries             BOOLEAN NOT NULL DEFAULT false,
    IsMensHairSalons             BOOLEAN NOT NULL DEFAULT false,
    IsFinancialServices             BOOLEAN NOT NULL DEFAULT false,
    IsDUILaw             BOOLEAN NOT NULL DEFAULT false,
    IsWomensClothing             BOOLEAN NOT NULL DEFAULT false,
    IsTapasAndSmallPlates             BOOLEAN NOT NULL DEFAULT false,
    IsOutdoorFurnitureStores             BOOLEAN NOT NULL DEFAULT false,
    IsHospitals             BOOLEAN NOT NULL DEFAULT false,
    IsPopcornShops             BOOLEAN NOT NULL DEFAULT false,
    IsRamen             BOOLEAN NOT NULL DEFAULT false,
    IsHomeEnergyAuditors             BOOLEAN NOT NULL DEFAULT false,
    IsPropane             BOOLEAN NOT NULL DEFAULT false,
    IsKaraoke             BOOLEAN NOT NULL DEFAULT false,
    IsApartmentAgents             BOOLEAN NOT NULL DEFAULT false,
    IsDanceSchools             BOOLEAN NOT NULL DEFAULT false,
    IsNotaries             BOOLEAN NOT NULL DEFAULT false,
    IsSocialSecurityLaw             BOOLEAN NOT NULL DEFAULT false,
    IsCardiologists             BOOLEAN NOT NULL DEFAULT false,
    IsHeatingAndAirConditioningAndHVAC             BOOLEAN NOT NULL DEFAULT false,
    IsNewspapersAndMagazines             BOOLEAN NOT NULL DEFAULT false,
    IsPetStores             BOOLEAN NOT NULL DEFAULT false,
    IsHerbsAndSpices             BOOLEAN NOT NULL DEFAULT false,
    IsSkateParks             BOOLEAN NOT NULL DEFAULT false,
    IsGolfEquipment             BOOLEAN NOT NULL DEFAULT false,
    IsTobaccoShops             BOOLEAN NOT NULL DEFAULT false,
    IsMoroccan             BOOLEAN NOT NULL DEFAULT false,
    IsFoodDeliveryServices             BOOLEAN NOT NULL DEFAULT false,
    IsFurnitureStores             BOOLEAN NOT NULL DEFAULT false,
    IsInternetServiceProviders             BOOLEAN NOT NULL DEFAULT false,
    IsHealthRetreats             BOOLEAN NOT NULL DEFAULT false,
    IsArchitects             BOOLEAN NOT NULL DEFAULT false,
    IsBedAndBreakfast             BOOLEAN NOT NULL DEFAULT false,
    IsSkateShops             BOOLEAN NOT NULL DEFAULT false,
    IsWatches             BOOLEAN NOT NULL DEFAULT false,
    IsPostOffices             BOOLEAN NOT NULL DEFAULT false,
    IsWineAndSpirits             BOOLEAN NOT NULL DEFAULT false,
    IsChallengeCourses             BOOLEAN NOT NULL DEFAULT false,
    IsBanksAndCreditUnions             BOOLEAN NOT NULL DEFAULT false,
    IsDiscGolf             BOOLEAN NOT NULL DEFAULT false,
    IsPilates             BOOLEAN NOT NULL DEFAULT false,
    IsWheelAndRimRepair             BOOLEAN NOT NULL DEFAULT false,
    IsCambodian             BOOLEAN NOT NULL DEFAULT false,
    IsTreeServices             BOOLEAN NOT NULL DEFAULT false,
    IsPediatricDentists             BOOLEAN NOT NULL DEFAULT false,
    IsInteriorDesign             BOOLEAN NOT NULL DEFAULT false,
    IsWhiskeyBars             BOOLEAN NOT NULL DEFAULT false,
    IsResorts             BOOLEAN NOT NULL DEFAULT false,
    IsSalvadoran             BOOLEAN NOT NULL DEFAULT false,
    IsRecreationCenters             BOOLEAN NOT NULL DEFAULT false,
    IsPainters             BOOLEAN NOT NULL DEFAULT false,
    IsScavengerHunts             BOOLEAN NOT NULL DEFAULT false,
    IsSpinClasses             BOOLEAN NOT NULL DEFAULT false,
    IsPickYourOwnFarms             BOOLEAN NOT NULL DEFAULT false,
    IsAllergists             BOOLEAN NOT NULL DEFAULT false,
    IsHospice             BOOLEAN NOT NULL DEFAULT false,
    IsBespokeClothing             BOOLEAN NOT NULL DEFAULT false,
    IsFleaMarkets             BOOLEAN NOT NULL DEFAULT false,
    IsMacarons             BOOLEAN NOT NULL DEFAULT false,
    IsPumpkinPatches             BOOLEAN NOT NULL DEFAULT false,
    IsSouvenirShops             BOOLEAN NOT NULL DEFAULT false,
    IsGasStations             BOOLEAN NOT NULL DEFAULT false,
    IsRockClimbing             BOOLEAN NOT NULL DEFAULT false,
    IsDaySpas             BOOLEAN NOT NULL DEFAULT false,
    IsReligiousOrganizations             BOOLEAN NOT NULL DEFAULT false,
    IsAsianFusion             BOOLEAN NOT NULL DEFAULT false,
    IsWaterHeaterInstallationRepair             BOOLEAN NOT NULL DEFAULT false,
    IsArabian             BOOLEAN NOT NULL DEFAULT false,
    IsHandyman             BOOLEAN NOT NULL DEFAULT false,
    IsCasinos             BOOLEAN NOT NULL DEFAULT false,
    IsBuffets             BOOLEAN NOT NULL DEFAULT false,
    IsNaturalGasSuppliers             BOOLEAN NOT NULL DEFAULT false,
    IsLeatherGoods             BOOLEAN NOT NULL DEFAULT false,
    IsPubFood             BOOLEAN NOT NULL DEFAULT false,
    IsPerfume             BOOLEAN NOT NULL DEFAULT false,
    IsElectronics             BOOLEAN NOT NULL DEFAULT false,
    IsMountainBiking             BOOLEAN NOT NULL DEFAULT false,
    IsAcaiBowls             BOOLEAN NOT NULL DEFAULT false,
    IsCivicCenter             BOOLEAN NOT NULL DEFAULT false,
    IsHawaiian             BOOLEAN NOT NULL DEFAULT false,
    IsGreek             BOOLEAN NOT NULL DEFAULT false,
    IsCandyStores             BOOLEAN NOT NULL DEFAULT false,
    IsHardwareStores             BOOLEAN NOT NULL DEFAULT false,
    IsAppliancesAndRepair             BOOLEAN NOT NULL DEFAULT false,
    IsCircuitTrainingGyms             BOOLEAN NOT NULL DEFAULT false,
    IsWaterHeaterInstallationAndRepair             BOOLEAN NOT NULL DEFAULT false,
    IsSecuritySystems             BOOLEAN NOT NULL DEFAULT false,
    IsTikiBars             BOOLEAN NOT NULL DEFAULT false,
    IsEatertainment             BOOLEAN NOT NULL DEFAULT false,
    IsLifeCoach             BOOLEAN NOT NULL DEFAULT false,
    IsFood             BOOLEAN NOT NULL DEFAULT false,
    IsAirDuctCleaning             BOOLEAN NOT NULL DEFAULT false,
    IsMortgageBrokers             BOOLEAN NOT NULL DEFAULT false,
    IsSouthern             BOOLEAN NOT NULL DEFAULT false,
    IsLebanese             BOOLEAN NOT NULL DEFAULT false,
    IsInternationalGrocery             BOOLEAN NOT NULL DEFAULT false,
    IsVinylRecords             BOOLEAN NOT NULL DEFAULT false,
    IsProfessionalServices             BOOLEAN NOT NULL DEFAULT false,
    IsTravelServices             BOOLEAN NOT NULL DEFAULT false,
    IsSzechuan             BOOLEAN NOT NULL DEFAULT false,
    IsElementarySchools             BOOLEAN NOT NULL DEFAULT false,
    IsTrainers             BOOLEAN NOT NULL DEFAULT false,
    IsDesserts             BOOLEAN NOT NULL DEFAULT false,
    IsSportingGoods             BOOLEAN NOT NULL DEFAULT false,
    IsBarreClasses             BOOLEAN NOT NULL DEFAULT false,
    IsAcneTreatment             BOOLEAN NOT NULL DEFAULT false,
    IsRotisserieChicken             BOOLEAN NOT NULL DEFAULT false,
    IsIndoorPlaycentre             BOOLEAN NOT NULL DEFAULT false,
    IsCaterers             BOOLEAN NOT NULL DEFAULT false,
    IsSeafoodMarkets             BOOLEAN NOT NULL DEFAULT false,
    IsSpeakeasies             BOOLEAN NOT NULL DEFAULT false,
    IsFurnitureAssembly             BOOLEAN NOT NULL DEFAULT false,
    IsDermatologists             BOOLEAN NOT NULL DEFAULT false,
    IsTrafficTicketingLaw             BOOLEAN NOT NULL DEFAULT false,
    IsDanceWear             BOOLEAN NOT NULL DEFAULT false,
    IsEyelashService             BOOLEAN NOT NULL DEFAULT false,
    IsArchery             BOOLEAN NOT NULL DEFAULT false,
    IsTattoo             BOOLEAN NOT NULL DEFAULT false,
    IsArchitecturalTours             BOOLEAN NOT NULL DEFAULT false,
    IsDialysisClinics             BOOLEAN NOT NULL DEFAULT false,
    IsJazzAndBlues             BOOLEAN NOT NULL DEFAULT false,
    IsOutletStores             BOOLEAN NOT NULL DEFAULT false,
    IsShoeStores             BOOLEAN NOT NULL DEFAULT false,
    IsThriftStores             BOOLEAN NOT NULL DEFAULT false,
    IsEndocrinologists             BOOLEAN NOT NULL DEFAULT false,
    IsLocalServices             BOOLEAN NOT NULL DEFAULT false,
    IsGlassAndMirrors             BOOLEAN NOT NULL DEFAULT false,
    IsShreddingServices             BOOLEAN NOT NULL DEFAULT false,
    IsLaundromat             BOOLEAN NOT NULL DEFAULT false,
    IsOutdoorGear             BOOLEAN NOT NULL DEFAULT false,
    IsPlacentaEncapsulations             BOOLEAN NOT NULL DEFAULT false,
    IsFastFood             BOOLEAN NOT NULL DEFAULT false,
    IsOilChangeStations             BOOLEAN NOT NULL DEFAULT false,
    IsPastaShops             BOOLEAN NOT NULL DEFAULT false,
    IsRVRental             BOOLEAN NOT NULL DEFAULT false,
    IsFashion             BOOLEAN NOT NULL DEFAULT false,
    IsWineries             BOOLEAN NOT NULL DEFAULT false,
    IsBikes             BOOLEAN NOT NULL DEFAULT false,
    IsDJs             BOOLEAN NOT NULL DEFAULT false,
    IsChocolatiersAndShops             BOOLEAN NOT NULL DEFAULT false,
    IsGraphicDesign             BOOLEAN NOT NULL DEFAULT false,
    IsBurgers             BOOLEAN NOT NULL DEFAULT false,
    IsPetServices             BOOLEAN NOT NULL DEFAULT false,
    IsComicBooks             BOOLEAN NOT NULL DEFAULT false,
    IsShavedSnow             BOOLEAN NOT NULL DEFAULT false,
    IsBatteryStores             BOOLEAN NOT NULL DEFAULT false,
    IsOphthalmologists             BOOLEAN NOT NULL DEFAULT false,
    IsBaseballFields             BOOLEAN NOT NULL DEFAULT false,
    IsMusicalInstrumentsAndTeachers             BOOLEAN NOT NULL DEFAULT false,
    IsFlooring             BOOLEAN NOT NULL DEFAULT false,
    IsChiropractors             BOOLEAN NOT NULL DEFAULT false,
    IsEndodontists             BOOLEAN NOT NULL DEFAULT false,
    IsHookahBars             BOOLEAN NOT NULL DEFAULT false,
    IsUrgentCare             BOOLEAN NOT NULL DEFAULT false,
    IsAirportLounges             BOOLEAN NOT NULL DEFAULT false,
    IsCustomsBrokers             BOOLEAN NOT NULL DEFAULT false,
    IsBowling             BOOLEAN NOT NULL DEFAULT false,
    IsAdultEducation             BOOLEAN NOT NULL DEFAULT false,
    IsNeurologist             BOOLEAN NOT NULL DEFAULT false,
    IsSwimmingPools             BOOLEAN NOT NULL DEFAULT false,
    IsNoodles             BOOLEAN NOT NULL DEFAULT false,
    IsCustomCakes             BOOLEAN NOT NULL DEFAULT false,
    IsEngraving             BOOLEAN NOT NULL DEFAULT false,
    IsOaxacan             BOOLEAN NOT NULL DEFAULT false,
    IsPianoBars             BOOLEAN NOT NULL DEFAULT false,
    IsLocalFishStores             BOOLEAN NOT NULL DEFAULT false,
    IsCoffeeAndTeaSupplies             BOOLEAN NOT NULL DEFAULT false,
    IsLaserTag             BOOLEAN NOT NULL DEFAULT false,
    IsFarms             BOOLEAN NOT NULL DEFAULT false,
    IsPaintAndSip             BOOLEAN NOT NULL DEFAULT false,
    IsPatisserieCakeShop             BOOLEAN NOT NULL DEFAULT false,
    IsAmusementParks             BOOLEAN NOT NULL DEFAULT false,
    IsTennis             BOOLEAN NOT NULL DEFAULT false,
    IsLifeInsurance             BOOLEAN NOT NULL DEFAULT false,
    IsMediterranean             BOOLEAN NOT NULL DEFAULT false,
    IsCandleStores             BOOLEAN NOT NULL DEFAULT false,
    IsHauntedHouses             BOOLEAN NOT NULL DEFAULT false,
    IsDistilleries             BOOLEAN NOT NULL DEFAULT false,
    IsPreschools             BOOLEAN NOT NULL DEFAULT false,
    IsGunsAndAmmo             BOOLEAN NOT NULL DEFAULT false,
    IsSocialClubs             BOOLEAN NOT NULL DEFAULT false,
    IsLaundryServices             BOOLEAN NOT NULL DEFAULT false,
    IsMeatShops             BOOLEAN NOT NULL DEFAULT false,
    IsBikeRentals             BOOLEAN NOT NULL DEFAULT false,
    IsHalal             BOOLEAN NOT NULL DEFAULT false,
    IsMotorcycleDealers             BOOLEAN NOT NULL DEFAULT false,
    IsDiagnosticImaging             BOOLEAN NOT NULL DEFAULT false,
    IsPaintball             BOOLEAN NOT NULL DEFAULT false,
    IsAutoCustomization             BOOLEAN NOT NULL DEFAULT false,
    IsLimos             BOOLEAN NOT NULL DEFAULT false,
    IsPlusSizeFashion             BOOLEAN NOT NULL DEFAULT false,
    IsCommunityServiceAndNonProfit             BOOLEAN NOT NULL DEFAULT false,
    IsParking             BOOLEAN NOT NULL DEFAULT false,
    IsTaxis             BOOLEAN NOT NULL DEFAULT false,
    IsBodyShops             BOOLEAN NOT NULL DEFAULT false,
    IsFishing             BOOLEAN NOT NULL DEFAULT false,
    IsWholesalers             BOOLEAN NOT NULL DEFAULT false,
    IsAerialFitness             BOOLEAN NOT NULL DEFAULT false,
    IsSepticServices             BOOLEAN NOT NULL DEFAULT false,
    IsCabaret             BOOLEAN NOT NULL DEFAULT false,
    IsMedicalSpas             BOOLEAN NOT NULL DEFAULT false,
    IsDryCleaningAndLaundry             BOOLEAN NOT NULL DEFAULT false,
    IsHealthMarkets             BOOLEAN NOT NULL DEFAULT false,
    IsThreadingServices             BOOLEAN NOT NULL DEFAULT false,
    IsOperaAndBallet             BOOLEAN NOT NULL DEFAULT false,
    IsUsedBookstore             BOOLEAN NOT NULL DEFAULT false,
    IsRealEstate             BOOLEAN NOT NULL DEFAULT false,
    IsPlasticSurgeons             BOOLEAN NOT NULL DEFAULT false,
    IsArtSupplies             BOOLEAN NOT NULL DEFAULT false,
    IsCountryClubs             BOOLEAN NOT NULL DEFAULT false,
    IsPackingServices             BOOLEAN NOT NULL DEFAULT false,
    IsHotels             BOOLEAN NOT NULL DEFAULT false,
    IsFoundationRepair             BOOLEAN NOT NULL DEFAULT false,
    IsJewelryRepair             BOOLEAN NOT NULL DEFAULT false,
    IsChurches             BOOLEAN NOT NULL DEFAULT false,
    IsArtsAndCrafts             BOOLEAN NOT NULL DEFAULT false,
    IsNurseriesAndGardening             BOOLEAN NOT NULL DEFAULT false,
    IsHealthCoach             BOOLEAN NOT NULL DEFAULT false,
    IsEthnicFood             BOOLEAN NOT NULL DEFAULT false,
    IsSignmaking             BOOLEAN NOT NULL DEFAULT false,
    IsKebab             BOOLEAN NOT NULL DEFAULT false,
    IsContractors             BOOLEAN NOT NULL DEFAULT false,
    IsKitchenAndBath             BOOLEAN NOT NULL DEFAULT false,
    IsMensClothing             BOOLEAN NOT NULL DEFAULT false,
    IsLatinAmerican             BOOLEAN NOT NULL DEFAULT false,
    IsAustrian             BOOLEAN NOT NULL DEFAULT false,
    IsPiercing             BOOLEAN NOT NULL DEFAULT false,
    IsMiddleSchoolsAndHighSchools             BOOLEAN NOT NULL DEFAULT false,
    IsShoeRepair             BOOLEAN NOT NULL DEFAULT false,
    IsElectricians             BOOLEAN NOT NULL DEFAULT false,
    IsPhotographers             BOOLEAN NOT NULL DEFAULT false,
    IsRealEstateAgents             BOOLEAN NOT NULL DEFAULT false,
    IsIrish             BOOLEAN NOT NULL DEFAULT false,
    IsToyStores             BOOLEAN NOT NULL DEFAULT false,
    IsAcupuncture             BOOLEAN NOT NULL DEFAULT false,
    IsAutoRepair             BOOLEAN NOT NULL DEFAULT false,
    IsJewelry             BOOLEAN NOT NULL DEFAULT false,
    IsPersianAndIranian             BOOLEAN NOT NULL DEFAULT false,
    IsAdultEntertainment             BOOLEAN NOT NULL DEFAULT false,
    IsMags             BOOLEAN NOT NULL DEFAULT false,
    IsPetSitting             BOOLEAN NOT NULL DEFAULT false,
    IsTexMex             BOOLEAN NOT NULL DEFAULT false,
    IsSalad             BOOLEAN NOT NULL DEFAULT false,
    IsBikeRepairAndMaintenance             BOOLEAN NOT NULL DEFAULT false,
    IsHairSalons             BOOLEAN NOT NULL DEFAULT false,
    IsMassageTherapy             BOOLEAN NOT NULL DEFAULT false,
    IsPhysicalTherapy             BOOLEAN NOT NULL DEFAULT false,
    IsKeysAndLocksmiths             BOOLEAN NOT NULL DEFAULT false,
    IsCulturalCenter             BOOLEAN NOT NULL DEFAULT false,
    IsCosmeticDentists             BOOLEAN NOT NULL DEFAULT false,
    IsJapanese             BOOLEAN NOT NULL DEFAULT false,
    IsWholesaleStores             BOOLEAN NOT NULL DEFAULT false,
    IsMiniGolf             BOOLEAN NOT NULL DEFAULT false,
    IsBridal             BOOLEAN NOT NULL DEFAULT false,
    IsMotorcycleGear             BOOLEAN NOT NULL DEFAULT false,
    IsOfficiants             BOOLEAN NOT NULL DEFAULT false,
    IsDanceClubs             BOOLEAN NOT NULL DEFAULT false,
    IsNightlife             BOOLEAN NOT NULL DEFAULT false,
    IsRaceTracks             BOOLEAN NOT NULL DEFAULT false,
    IsSwimmingLessonsSchools             BOOLEAN NOT NULL DEFAULT false,
    IsEthiopian             BOOLEAN NOT NULL DEFAULT false,
    IsPubs             BOOLEAN NOT NULL DEFAULT false,
    IsFingerprinting             BOOLEAN NOT NULL DEFAULT false,
    IsFilipino             BOOLEAN NOT NULL DEFAULT false,
    IsFirewood             BOOLEAN NOT NULL DEFAULT false,
    IsSugaring             BOOLEAN NOT NULL DEFAULT false,
    IsMattresses             BOOLEAN NOT NULL DEFAULT false,
    IsCheeseShops             BOOLEAN NOT NULL DEFAULT false,
    IsAutoDetailing             BOOLEAN NOT NULL DEFAULT false,
    IsLocalFlavor             BOOLEAN NOT NULL DEFAULT false,
    IsOralSurgeons             BOOLEAN NOT NULL DEFAULT false,
    IsObstetriciansAndGynecologists             BOOLEAN NOT NULL DEFAULT false,
    IsDinnerTheater             BOOLEAN NOT NULL DEFAULT false,
    IsCzech             BOOLEAN NOT NULL DEFAULT false,
    IsWaterPurificationServices             BOOLEAN NOT NULL DEFAULT false,
    IsFormalWear             BOOLEAN NOT NULL DEFAULT false,
    IsChristmasTrees             BOOLEAN NOT NULL DEFAULT false,
    IsEmbroideryAndCrochet             BOOLEAN NOT NULL DEFAULT false,
    IsDonationCenter             BOOLEAN NOT NULL DEFAULT false,
    FOREIGN KEY (BusinessID) REFERENCES Business(BusinessID),
    PRIMARY KEY (BusinessID)
);